version: "3"
services:
  python-proxy:
    build: .
    env_file: "config.txt"
    ports:
      - "80:80"
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_PROFILE=local-bedrock-testing
