version: "3"
services:
  python-proxy:
    build: .
    env_file: "config.txt"
    ports:
      - "80:80"
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=bedrock_development
